### ISSUE TITLE
Cannot run test for debug scheme because of duplicated testing targets

### ISSUE THREAD

**Issue by jasonnam** [ttkien/clean-architecture-with-swift-and-testing#13]
<img width="670" alt="Screen Shot 2019-04-22 at 15 50 16" src="https://user-images.githubusercontent.com/3154042/56492573-6b931d00-6516-11e9-830a-fb61cb68cfd2.png">

**Comment by ttkien** [comment]
- I checked it and don't know why you get that. I attached a video to show UseCasesTests and SurveyManagerUITests can run perfectly. I only test 2 frameworks because they contain logic and the others have no logic
- I used Quick, Nimble and KIF to write Testing

Video:
https://photos.app.goo.gl/sbXSGNQzMzCzqKCE6
